[build]
  command = "npm run build && pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"