[build]
  # Build static site into dist and publish it
  command = "python3 build_static.py"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

## No serverless functions required for static site
## [functions]
##   directory = "netlify/functions"

## Optional SPA-style fallback for unmatched paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"